### ISSUE TITLE
How to build a dll file？

### ISSUE THREAD

**Issue by DZQ-Niente** [CoppeliaRobotics/simExtJoystick#1]
I put the “simExtJoystick” folder in “C:\Program Files\CoppeliaRobotics\CoppeliaSimPro”，and use visual studio 2019 to open the “simExtJoystick” folder, but I meet some problems:
1.  simExtJoystick.cpp have some include error, and I use absolute path to solve.
2. Then, I meet the erros is: 
D:\Windows Kits\10\Include\10.0.19041.0\um\dinput.h: DIRECTINPUT_VERSION undefined. Defaulting to version 0x0800
1>C:\Program Files\CoppeliaRobotics\CoppeliaSimPro\programming\include\simLib\simExp.h(9,1): fatal error C1189: #error:  Define one of WIN_SIM, MAC_SIM or LIN_SIM

**Comment by DZQ-Niente** [comment]
Could you provide dll files directly?

**Comment by Coppelia** [comment]
Hello, the Joystick plugin has been discontinued, since it was Windows only. Nowadays, best would be to use a Python script in CoppeliaSim that offers joystick functionality via a specific package, e.g.: pygame, pyjoystick
Cheers
